### ISSUE TITLE
Add dependency bounds.

### ISSUE THREAD

**Issue by phadej** [haskell-servant/servant#533] opened 2016-07-05 12:47 UTC
`http-client` issue is a good example why we should have them.

I can make a PR adding them, with lower-bounds from say *Stackage lts-2.22*, and upper-bounds allowing current major versions (if they do work, of course).

**Comment by arianvp** [comment] 2016-07-05 14:32
duplicate of #534

**Closed by arianvp** 2016-07-05 14:32 UTC

**Comment by phadej** [comment] 2016-07-05 14:33
Hups. Sorry.
