### ISSUE TITLE
serveDirectory does not seem to work with enter and custom handler monads

### ISSUE THREAD

**Issue by mrkkrp** [haskell-servant/servant#549] opened 2016-07-11 17:09 UTC
Our API looks like this:

```haskell
type Routes  = HomeR :<|> … :<|> StaticR
…
type StaticR = "static" :> Raw

handlers :: ServerT Routes App
handlers = homeR :<|> … :<|> staticR

—

staticR :: Application
staticR = serveDirectory "static/"
```

It's run like this:

```haskell
app :: AppContext -> Application
app appContext@AppContext {..} = serveWithContext
  (Proxy :: Proxy Routes)
  (authCheck appContextPool :. EmptyContext)
  (server appContext)

server :: AppContext -> Server Routes
server context = enter (runContext context) handlers

runContext :: AppContext -> App :~> Handler
runContext context = Nat $ flip runReaderT context
```

When we started to use `serveDirectory`, the following error manifested itself:

```
Couldn't match type ‘IO’
               with ‘transformers-0.4.2.0:Control.Monad.Trans.Except.ExceptT
                       ServantErr IO’
arising from a functional dependency between:
  constraint ‘Servant.Utils.Enter.Enter
                (IO ResponseReceived) (App :~> Handler) (IO ResponseReceived)’
    arising from a use of ‘enter’
  instance ‘Servant.Utils.Enter.Enter (m a) (m :~> n) (n a)’
    at <no location info>
In the expression: enter (runContext context) handlers
In an equation for ‘server’:
    server context = enter (runContext context) handlers
```

If we remove `staticR` stuff, everything is OK. Should we use a different method to serve static files when we use custom handler monad or it's a bug?

**Comment by codedmart** [comment] 2016-07-11 17:21
@mrkkrp This is a known issue -> https://github.com/haskell-servant/servant/issues/157. I had a PR a while ago for this, but it was never finalized or accepted -> https://github.com/haskell-servant/servant/pull/178.

**Comment by soenkehahn** [comment] 2016-08-11 14:19
Duplicate of #157, closing.

Note this workaround: https://groups.google.com/d/msg/haskell-servant/jhDWkAZixuI/Hkm8CBAuEQAJ

**Closed by soenkehahn** 2016-08-11 14:19 UTC
