### ISSUE TITLE
transformers-0.5

### ISSUE THREAD

**Issue by andrewthad** [haskell-servant/servant#450] opened 2016-04-07 14:57 UTC
I'm using `transformers-0.5.1.0` in a project, and `servant-server` does not allow that. Can the upper bound be bumped?

**Comment by soenkehahn** [comment] 2016-04-12 07:11
Sure, do you want to come up with a PR?

**Comment by kosmikus** [comment] 2016-04-12 09:48
@soenkehahn The transformers change is a part of the (open) PR #388.

**Comment by soenkehahn** [comment] 2016-04-12 09:53
I see. So should we merge #388 then?

Note that since 1920694f `ghc-8` will be rejected by cabal. (And I don't want to lift that restriction until we have CI for `ghc-8`.)

**Comment by kosmikus** [comment] 2016-04-12 10:05
I think we should merge #388 or #385, yes. I'd also like to lift the base restriction. What's keeping us from having CI for ghc-8?

**Comment by kosmikus** [comment] 2016-04-12 10:09
@soenkehahn Nevermind, seen all the discussion on #385. Perhaps easiest for now is to just merge #388 as a definitely good step towards compatibility with GHC-8.

**Comment by soenkehahn** [comment] 2016-04-12 10:13
Yes, agreed.

Well, I actually don't understand why this is necessary and wasn't before:

https://github.com/haskell-servant/servant/pull/388/files#diff-967abff9d6f0ae3f0ae966b89b7cc939R173

I haven't had the time to look into it. But apart from that I'm not against merging #388.

**Comment by kosmikus** [comment] 2016-04-12 16:18
@soenkehahn It's a known regression in ghc-8's typechecker that will probably not be fixed, as it is a side-effect of adding support for recursive superclasses. See https://ghc.haskell.org/trac/ghc/ticket/11762 and https://ghc.haskell.org/trac/ghc/ticket/11427.

The additional constraints should not do any harm for ghc-7 though, so #388 should be safe to merge.

**Comment by soenkehahn** [comment] 2016-04-13 10:30
@kosmikus: Thanks for the pointers. Do you want to go ahead and merge than?

**Comment by kosmikus** [comment] 2016-04-13 13:11
Closed via #388.

**Closed by kosmikus** 2016-04-13 13:11 UTC
