### ISSUE TITLE
Should accept mismatches affect routing?

### ISSUE THREAD

**Issue by MichaelXavier** [haskell-servant/servant#460] opened 2016-04-11 18:35 UTC
First off, apologies if this is covered somewhere, but I couldn't find it.

I'm porting an existing API to servant and noticed a curious behavior with routing. I've got an endpoint that can return either JSON or CSV content. The CSV API has query params that are relevant only to it and since query params are part of the type, I split the route. Here's an example using plaintext:

```haskell
{-# LANGUAGE DataKinds             #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings     #-}
{-# LANGUAGE TypeOperators         #-}
module Main where

import           Data.Aeson
import           Network.Wai.Handler.Warp
import           Servant

data Bar = Bar

instance ToJSON Bar where
  toJSON Bar = String "Bar"

instance MimeRender PlainText Bar where
  mimeRender _ Bar = "Bar"

type API
    = Get '[JSON] Bar
 :<|> QueryParam "n" Int :> Get '[PlainText] Bar

server :: Server API
server = jsonBar :<|> plainBar

jsonBar = return Bar

plainBar _ = return Bar

api :: Proxy API
api = Proxy

main = run 8000 (serve api server)
```

If you make an unqualified `GET http://localhost:8000`, it returns "Bar" with an `application/json content type`. That seems fine. If you make the same get with `Accept: text/plain`, you'll get a 406 Not Acceptable. I would expect the router logic to:

1. Check for an Accept. If none is provided, simply find the first route that matches (it does this today, but perhaps by coincidence).
2. If 1 or more accepts are supplied, find a route whose content type includes one of the given accept content types.
3. Failing all that, throw the 406.

I don't know the internals but it seems like route matching and accept checking are 2 distinct, sequential steps rather than being 1 or doing any sort of backtracking.

In the mean time, the workaround seems to be to combine routes and ignore irrelevant params, but it isn't clear to me how a server handler can know the media type requested, as all the rendering gets taken care of at the typeclass level. Maybe I could add the accept or media type to the route segments and it will get passed in as an argument?

**Comment by kosmikus** [comment] 2016-04-11 18:54
For some reason, if the `acceptCheck` fails, `FailFatal` is being used and other routes are no longer tried. I think this is wrong, but then again I'm known for generally opposing the idea of using `FailFatal` in most cases, whereas others think it's a good idea :)

So personally, I think you're right. Your example should work. And it would be a one-line fix to make it work.

It looks like this actually has been using a normal `Fail` at one point, but then was changed by @jkarni in 1aeee3ef9403251fbc500ee3e3df91f699ed54b3 while removing `memoReqBody`. I currently don't see why the two issues are connected, as the body check should be run last, after the accept method check.

**Comment by kosmikus** [comment] 2016-04-11 19:44
Oh, I see now. I was wrong.

Ok, here is an attempt at explaining the dilemma:

We're roughly trying to follow https://github.com/for-GET/http-decision-diagram
This specifies that the request body has to be checked prior to the Accept. If the request body is incorrect, 400 is returned. If the accept check fails, 406 is returned.

The problem is that we can check the request body only once if we want to maintain the option to stream large requests. Checking the contents of the request body multiple times would mean we have to keep the entire body in memory in between checks. Therefore, after the request body has been checked once, we cannot backtrack to other routes anymore.

I'm pretty sure that this is the reason why @jkarni changed the `Fail` in the accept check into a `FailFatal`. In general, the Accept check may happen after the body has been checked. So we pessimistically have to fail fatally.

Now in your example, there is no request body involved. It is conceivable to change the code so that the accept check only fails fatally if there actually is a request body to be checked. However, that is still somewhat unsatisfactory. I'm also currently not sure (but perhaps someone else can clarify) if request body streaming is actually supposed to work now with the standard `ReqBody` combinator, and if so, how that is compatible with "checking" it in advance. Obviously, if the check is forcing the entire request body, that's also defeating the idea of streaming.

**Comment by soenkehahn** [comment] 2016-04-12 04:53
I added this test-case:

https://github.com/haskell-servant/servant/commit/97168459fd7c9ad253389191ce4a527784a706fd

It makes sure that streaming with `ReqBody` works in principle, but only for `ByteString`. Of course, no validation happens there.

I suspect that streaming of e.g. `JSON` does not work currently in cause of validation. I think the best approach for streaming `JSON` would be to add another way of receiving `JSON` that decodes to some producer from e.g. `pipes-aeson`. (This could be done in a separate package.) This would allow streaming while leaving the handling of decoding errors to the `Handler`s.

**Comment by kosmikus** [comment] 2016-04-12 08:40
The #461 PR should fix your problem. It changes overall behaviour though, so we should discuss whether this is what we really want to do before we merge.

**Comment by soenkehahn** [comment] 2016-04-18 09:41
Since #461 was merged I'll close this issue. Please reopen if this is incorrect.

**Closed by soenkehahn** 2016-04-18 09:41 UTC
