### ISSUE TITLE
Generated JavaScript function naming collision

### ISSUE THREAD

**Issue by parsonsmatt** [haskell-servant/servant#143] opened 2015-06-23 16:30 UTC
Given an API type:
```haskell
type ExampleAPI = "resources" :> Get '[Text] [String]
             :<|> "resources" :> Capture "id" Int :> Get '[Text] String
```
The generated jQuery looks like:
```js
function getresources(onSuccess, onError) { /* ... */ }
function getresources(id, onSuccess, onError) { /*...*/ }
```
Since JavaScript doesn't have function overloading, the second function overrides the first one.

This is related to #39, and I think a solution to that issue would fix this as well. The code that I'd *like* to generate would look something like:
```js
function getResource(id, onSuccess, onError) {}
function getResources(onSuccess, onError) {}
```
where the name generator can infer (or is told about) a singular vs collection resource and pluralize the function name appropriately. In addition to a camelCase formatter, you could pass a function to resolve name collisions. We'd also want this to be generalizable for languages with other semantics around function overloading. Java would have no problem with the above example, for instance.

I'd like to contribute here, and I have some ideas for how it might be handled. Before getting started, I'd like to know what other people's takes are on this, and what the best solution might be.

A current work-around is to give the resources different names, but this breaks RESTful resource naming in URLs: `resources` vs `resource/:id`

**Comment by alpmestan** [comment] 2015-06-24 10:30
Hello @parsonsmatt,

Yes, the way we generate function names is hacky at best. But we needed something, to get the ball rolling and actually publish this package. The problem being that with the huge focus of everyone on *servant* and *servant-server*, we haven't taken much time to re-engineer this bit of *servant-jquery*, one of the reasons, I think, being that it's not used all that much.

If you are willing to give it a shot, I can help you understand anything unclear in the code and would stay around for any question. I unfortunately don't have time to tackle this myself these days but would more than glad to help you do it. The first thing you have to do really is "simply" to find an algorithm to generate  the function name just using whatever combinators you see on the way.

The way it works now is that in many (but not all) `HasJQ` instances, we add something to the front of the "current name", [e.g](https://github.com/haskell-servant/servant/blob/master/servant-jquery/src/Servant/JQuery/Internal.hs#L218):

``` haskell
instance Elem JSON list => HasJQ (Delete list a) where
  type JQ (Delete list a) = AjaxReq

  jqueryFor Proxy req =
    req & funcName  %~ ("delete" <>)  -- HERE: we prepend "delete" to the current function name
        & reqMethod .~ "DELETE"
```

So this is all you would have to modify: all the places where we tweak `funcName`. The trick being that ideally we want an algorithm that will generate different names for 2 endpoints that are "different enough".

I'll let you brainstorm about this now, feel free to get in touch on IRC (**#servant** on freenode) or to just keep discussing this here, I'll do my best to help you land a patch for this.

**Comment by parsonsmatt** [comment] 2015-06-24 13:51
Cool! :) I'll be glad to help out. I'll study the current implementation a bit more and see other potential solutions. I'll also consider @rtrvrtg's implementation. When I've got a few ideas, I'll comment and we can discuss. Thanks!

**Comment by jkarni** [comment] 2015-07-09 12:33
@parsonsmatt This seems like a duplicate of #38 ? (Maybe that should have a more informative name, or that one should be closed in favour of this one)

**Comment by alpmestan** [comment] 2015-07-29 13:29
The recent work by @freezeboy largely mitigates this issue. See #161 and #171. This basically lets the user tweak the way function names are generated, from the components and also provides various options to tweak the output. I believe this fixes this issue so I'm closing it, but if you're not satisfied with that feel free to reopen it and explain why it doesn't work fory ou. You can learn how this can be used by looking at the documentation in `servant-js/src/Servant/JS.hs`, in the *master* branch.

**Closed by alpmestan** 2015-07-29 13:29 UTC
Labels: bug, servant-jquery

**Comment by parsonsmatt** [comment] 2015-07-29 14:13
:+1: very cool! :D
