### ISSUE TITLE
BasicAuth does not distribute over :<|>

### ISSUE THREAD

**Issue by tommyengstrom** [haskell-servant/servant#558] opened 2016-07-27 19:57 UTC
Given a simple API and client
``` Haskell
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeOperators #-}

import Servant
import Servant.Client
import Control.Monad.Except
import Network.HTTP.Client (Manager)

type API = "a" :> Get '[JSON] String
      :<|> "b" :> Get '[JSON] String

api :: Proxy API
api = Proxy

getA :: Manager -> BaseUrl -> ExceptT ServantError IO String
getB :: Manager -> BaseUrl -> ExceptT ServantError IO String
getA :<|> getB = client api
```
I was expecting to be able to add authorization like this:
``` Haskell
type BA = BasicAuth "role" Bool

authApi1 :: Proxy AuthAPI1
authApi1 = Proxy

type AuthAPI1 = BA :> API

auth1GetA :: BasicAuthData -> Manager -> BaseUrl -> ExceptT ServantError IO String
auth1GetB :: BasicAuthData -> Manager -> BaseUrl -> ExceptT ServantError IO String
auth1GetA :<|> auth1GetB = client authApi1

```
But the client fails to compile with error

```
 Couldn't match type ‘BasicAuthData
                         -> (Manager -> BaseUrl -> ClientM [Char])
                            :<|> (Manager -> BaseUrl -> ClientM [Char])’
                   with ‘t :<|> t1’
    Expected type: t :<|> t1
      Actual type: Client AuthAPI1
    Relevant bindings include
      auth1GetA :: t (bound at Bug.hs:29:1)
      auth1GetB :: t1 (bound at Bug.hs:29:16)
    In the expression: client authApi1
    In a pattern binding: auth1GetA :<|> auth1GetB = client authApi1
```
But the following works fine
```Haskell 
type AuthAPI2 = BA :> "a" :> Get '[JSON] String
       :<|> BA :> "b" :> Get '[JSON] String

authApi2 :: Proxy AuthAPI2
authApi2 = Proxy


auth2GetA :: BasicAuthData -> Manager -> BaseUrl -> ExceptT ServantError IO String
auth2GetB :: BasicAuthData -> Manager -> BaseUrl -> ExceptT ServantError IO String
auth2GetA :<|> auth2GetB = client authApi2
```

After talking to @arianvp it is my understanding that authAPI1 and authAPI2 is intended to be equivalent.

**Comment by arianvp** [comment] 2016-07-27 20:55
Thanks for the good report!

Ping @aaronlevin do you remember if we didn't distribute on purpose?

**Comment by aaronlevin** [comment] 2016-07-27 22:41
@arianvp you can distribute it, but the way you write the handlers needs to be different. I think you need to do something like: `authHandler :> (getA :<|> getB)` or something. I'm pretty sure I've done this (I can't put together an example right in this moment).

**Comment by lethom** [comment] 2016-07-28 07:14
I remember doing something like this.

**Comment by chris-kahn** [comment] 2016-09-04 00:18
I've also run into this exact problem, trying to create a client to an API that is wrapped using `AuthProtect`.

**Comment by jkarni** [comment] 2016-09-04 01:42
Unless I'm misunderstanding something, this is the normal behavior. In general

     A :> (B :<|> C)  ===> a -> (b :<|> c)
     (A :> B) :<|> (A :> C) ===> (a -> b :<|> a -> c)

And this is true for all combinators, and both client functions and handlers.

It's possible to write a function to convert between these, however. [Here](https://github.com/haskell-servant/servant/pull/23/files#diff-a410ed522fbe5bf160e2301261979e6dR96) is an example.

**Comment by arianvp** [comment] 2016-09-04 08:58
Yes I agree this is normal behavior.  It was a bit confusing for some reason but it's not an actual issue. I think it is nice to put an example in the tutorial that is a bit more advanced.

**Comment by alpmestan** [comment] 2016-09-04 10:20
+1 for the example.

**Comment by chris-kahn** [comment] 2016-09-04 10:56
In theory it shouldn't be an issue, no, `a :> (b :<|> c) ` should be equivalent to `a :> b :<|> a :> c` from the perspective of an API client. Thanks for the example, I'll try this. I definitely think this needs to go in the documentation, any realistic API client is going to run into this compilation error.

**Comment by chkl** [comment] 2016-09-04 12:06
I put together a simple example that uses BasicAuth(https://github.com/chkl/example-servant-auth). The relevant part is
```haskell
server :: Server API 
server user = hListIssues :<|> hGetIssue :<|> (hWhoami user)
```

Maybe it would make sense to include the whole or part of it into the tutorial.

**Comment by chris-kahn** [comment] 2016-09-04 12:43
Your example API should have a little more depth to encounter the problem referenced in this issue. Create at least one branch/subtree, for example, provide both a Puclic and Private API and make sure the credentials are not known at compile time. Try to create a client for this type:

    type MyAPI = "public" :> Get '[JSON] Text
            :<|> "private" :> BasicAuth "TestRealm" User :> (Get '[JSON] Text 
                                                         :<|> Post '[JSON] Text)

    myAPI :: Proxy MyAPI
    myAPI = Proxy

    -- and achieve flattened client functions like this:
    getPublic :: Manager -> BaseUrl -> ClientM Text
    getPrivate :: BasicAuthData -> Manager -> BaseUrl -> ClientM Text 
    postPrivate :: BasicAuthData -> Manager -> BaseUrl -> ClientM Text

    (getPublic :<|> getPrivate :<|> postPrivate) = client myAPI

    -- so that I can call a private function with credentials known only at runtime
    callingFunction :: Manager -> BaseUrl -> String -> String -> ClientM ()
    callingFunction manager baseUrl username password = do
        resultText <- postPrivate (BasicAuthData (pack username) (pack password))
        -- do more stuff

**Comment by chris-kahn** [comment] 2016-09-04 12:52
Of course it's possible to write:

    (getPublic :<|> privateAPI) = client myAPI

And then inside `callingFunction` write something like...
    
    let (getPrivate :<|> postPrivate) = privateAPI (BasicAuthData (pack username) (pack password))
    resultText <- postPrivate

But in any non-trivial API client the left-hand side will be somewhat complex and will be repeated many times. Ideally I should be able to define my list of client functions once and only once. In theory the Canonicalize example should achieve this, but so far I'm having problems making it work...

**Comment by alpmestan** [comment] 2016-09-04 14:30
`Canonicalize` should be used as follows:

``` haskell
(client1 :<|> client2 :<|> ... :<|> clientN) = client (canonicalize myAPI)
```

**Comment by jkarni** [comment] 2016-09-04 14:57
Closing, though if there are questions we can continue discussing them here.

**Closed by jkarni** 2016-09-04 14:57 UTC
Labels: bug

**Comment by chris-kahn** [comment] 2016-09-04 14:59
Ok. I've included the Canonicalize type family and tried exactly that line of code and still get an error...

  Couldn't match type ‘BasicAuthData
                       -> (Manager -> BaseUrl -> ClientM Text)
                          :<|> (Manager -> BaseUrl -> ClientM Text)’
                 with ‘t :<|> t1’
  Expected type: (Manager -> BaseUrl -> ClientM Text)
                 :<|> (t :<|> t1)
    Actual type: Client
                   (("public" :> Get '[JSON] Text)
                    :<|> ("private"
                          :> (BasicAuth "testParam" Text
                              :> (Get '[JSON] Text :<|> Post '[JSON] Text))))
  Relevant bindings include
    getPrivateText :: t (bound at src/Lib.hs:32:21)
    postPrivateText :: t1 (bound at src/Lib.hs:32:41)
  In the expression: client (canonicalize myAPI)
  In a pattern binding:
    (getPublicText :<|> getPrivateText :<|> postPrivateText)
      = client (canonicalize myAPI)

**Comment by chris-kahn** [comment] 2016-09-04 15:00
Based on "Actual type" section it doesn't look like it really canonicalized the type.... am I missing something obvious?

**Comment by jkarni** [comment] 2016-09-04 15:05
Hm, interesting. @alpmestan ?

**Comment by chris-kahn** [comment] 2016-09-04 15:14
I created a repo to show what I'm trying to do:

https://github.com/chris-kahn/servant-client-example/blob/master/src/Lib.hs

**Comment by alpmestan** [comment] 2016-09-05 22:49
Hey @chris-kahn, sorry for the inconvenience! This is due to a stupid mistake from me in the definition for `Canonicalize`. Looks at these two lines:

```  haskell
  Canonicalize (a :> (b :<|> c)) = a :> Canonicalize b :<|> a :> Canonicalize c
  Canonicalize ((a :<|> b) :> c) = a :> Canonicalize c :<|> b :> Canonicalize c
```

In the case where `b` (2nd line) or `c` (1st line) is not the last "route" but is actually several other routes glued together with `:<|>`, we just skip any "distribution" we can perform in there and go straight to what follows. What if you change your `Canonicalize` definition to:

``` haskell
type family Canonicalize api :: * where
  -- requires UndecidableInstances
  Canonicalize (a :> (b :<|> c)) = a :> Canonicalize b :<|> (Canonicalize (a :> c))
  Canonicalize ((a :<|> b) :> c) = a :> Canonicalize c :<|> (Canonicalize (b :> c))
  Canonicalize (a :> b)          = Redex b (Canonicalize b) a
  Canonicalize (a :<|> b)        = Canonicalize a :<|> Canonicalize b
  Canonicalize a                 = a
```

**Comment by chris-kahn** [comment] 2016-09-06 00:53
I've updated this file in my repo... it seems like nothing has changed with the error message though. Actual type is still the original tree of routes.

**Comment by chris-kahn** [comment] 2016-09-06 01:11
I'm playing with the API to try to see what it's doing... it seems like it's only matching once and not recursing deeper. If I change the API to this:

    type MyAPI = BasicAuth "MyRealm" Text :> ("all" :> Get '[JSON] Text
                                                      :<|> "foo" :> Capture "bar" Text :> (Get '[JSON] Text :<|> Post '[JSON] Text))

I can see that it distributes the BasicAuth part but then it doesn't go deeper into the "foo" route. Any idea why this is?

**Comment by alpmestan** [comment] 2016-09-06 11:27
Alright, I'm now toying around with your code. I noticed something interesting.

Little note: to see what `Canonicalize SomeAPIType` actually resolves to, you can fire up `ghci` (or `cabal repl`, or the equivalent for stack) with those modules loaded and ask for:

``` haskell
*Lib> :kind! Canonicalize BigAPI2
```

The `:kind!` command is documented on [this page](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/ghci.html) (look for `:kind` on that page). I have used this extensively to figure out what's wrong with `Canonicalize`.

With the following:

```  haskell
type MyAPI = "private" :> BasicAuth "MyRealm" Text :> ("all" :> Get '[JSON] Text
                                                  :<|> "foo" :> Capture "bar" Text :> (Get '[JSON] Text 
                                                                                  :<|> Post '[JSON] Text))
```

`Client (Canonicalize MyAPI)`  is:

``` haskell
BasicAuthData
     -> (Manager -> BaseUrl -> ClientM Text)
        :<|> (Text
              -> (Manager -> BaseUrl -> ClientM Text)
                 :<|> (Manager -> BaseUrl -> ClientM Text))
```

However, if we remove the `"private"` bit, leaving everything else untouched, we now get:

```  haskell
(BasicAuthData -> Manager -> BaseUrl -> ClientM Text)
     :<|> (BasicAuthData
           -> Text
           -> (Manager -> BaseUrl -> ClientM Text)
              :<|> (Manager -> BaseUrl -> ClientM Text))
```

So at least here the `BasicAuthData` got distributed (but not the inner `Text` argument corresponding to the capture). So it seems that static path fragments are getting in the way, somehow.

I have reproduced the problem you mention with this simpler API:

```  haskell
type API = "foo" :> Capture "a" Int :> (Get '[JSON] Text :<|> Post '[JSON] Text)
```

Removing the static path prefix makes `Canonicalize` work as expected, but calling it on this `API` doesn't distribute the `Capture`.

This made me think of a possible explanation for those troubles. Indeed, if we instead have:

``` haskell
data Path (p :: Symbol)

type API2 = Path "foo" :> Capture "a" Int :> (Get '[JSON] Text :<|> Post '[JSON] Text)
```

Then `Canonicalize`ing that distributes the capture. Even better, if we try this trick on your original API, using `Path "some_path"`  wherever you wrote `"some_path"`:

``` haskell
type BigAPI2 = Path "public" :> Get '[JSON] Text
         :<|> Path "private" :> BasicAuth "MyRealm" Text :> (Path "all" :> Get '[JSON] Text
                                                        :<|> Path "foo" :> Capture "bar" Text :> (Get '[JSON] Text 
                                                                                        :<|> Post '[JSON] Text))
```

Then `Canonicalize` does distributed _everything_ as expected. So, what's going on?

Well, `Canonicalize` as defined above only is concerned with arguments of kind `*` so whenever it sees a type-level string, which has kind `Symbol` (if you're not familiar with those things, [this blog post](http://www.arow.info/blog/posts/2015-07-10-servant-intro.html) and [this one](https://www.well-typed.com/blog/2015/11/implementing-a-minimal-version-of-haskell-servant/) might help), it just gives up trying to transform anything further. It (probably?) just falls into the last clause (`Canonicalize a = a`) or something. Anyway, try with this new version of `Canonicalize`, without forgetting the `{-# LANGUAGE PolyKinds #-}` language extension at the top:

``` haskell
type family Canonicalize (api :: k) :: kwhere
  -- requires UndecidableInstances
  Canonicalize ((a :: k) :> (b :<|> c)) = a :> Canonicalize b :<|> (Canonicalize (a :> c))
  Canonicalize ((a :<|> b) :> c) = a :> Canonicalize c :<|> (Canonicalize (b :> c))
  Canonicalize ((a :: k) :> b)          = Redex b (Canonicalize b) a
  Canonicalize (a :<|> b)        = Canonicalize a :<|> Canonicalize b
  Canonicalize (a :: k)          = a

type family Redex a b (c :: k) :: * where
  Redex a a first = Canonicalize first :> a
  Redex a b first = Canonicalize (first :> b)
```

I basically just changed a few places to say that arguments can take any kind instead of just `*`, in order to allow type-level strings to be treated the same as other entities in the servant DSL. If this is not clear or if you have trouble making it work, I can send a PR to your repo. Sorry for the lengthy message by the way, I've been thinking out loud here while debugging your issue.

**Comment by chris-kahn** [comment] 2016-09-06 12:04
You're right! It was choking on the string paths, and after making this change it compiles without error. This is a learning experience for me, I'm still quite unfamiliar with this type level stuff and how to debug it.

Now I can build a more complex API and derive a flat set of client functions.

Thanks for your help, it's very much appreciated!

**Comment by alpmestan** [comment] 2016-09-06 14:37
Glad to help! Let me know if you encounter another problem with `Canonicalize`. Maybe I should package it up...
